blank_issues_enabled: false
contact_links:
  - name: Author's QQ
    url: tencent://AddContact/?fromId=50&fromSubId=1&subcmd=all&uin=1445018848
    about: The right place for asking quesions and getting support
